default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  username: valucon
  password: valucon
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: valucon_dev

test:
  <<: *default
  database: valucon_test
